const ASSIGN_ROOM = "ASSIGN_ROOM";
const START_GAME = "START_GAME";
const NEW_MEMBER = "NEW_MEMBER";
const ADD_VOTE = "ADD_VOTE";
const ADD_MESSAGE = "ADD_MESSAGE";
const ADD_STORY = "ADD_STORY";
const DELETE_STORY = "DELETE_STORY";
const EDIT_STORY = "EDIT_STORY";
const EDIT_HISTORY = "EDIT_HISTORY";
const USER_VOTE = "USER_VOTE";
const FLIP_CARDS = "FLIP_CARDS";
const DELETE_VOTES = "DELETE_VOTES";
const END_GAME = "END_GAME";
const RESET_TIMER = "RESET_TIMER";
const SOCKET_ROOM_CREATED = "SOCKET_ROOM_CREATED";
export const ADD_TOAST = "ADD_TOAST";
export const REMOVE_TOAST = "REMOVE_TOAST";

export {
  ASSIGN_ROOM,
  START_GAME,
  NEW_MEMBER,
  ADD_VOTE,
  ADD_MESSAGE,
  ADD_STORY,
  DELETE_STORY,
  EDIT_STORY,
  EDIT_HISTORY,
  USER_VOTE,
  FLIP_CARDS,
  DELETE_VOTES,
  END_GAME,
  RESET_TIMER,
  SOCKET_ROOM_CREATED
};
