const CREATE_ROOM = "CREATE_ROOM";
const JOIN_ROOM = "JOIN_ROOM";
const REJOIN_ROOM = "REJOIN_ROOM";
const START_GAME = "START_GAME";
const NEW_MEMBER = "NEW_MEMBER";
const ADD_VOTE = "ADD_VOTE";
const ADD_STORY = "ADD_STORY";
const DELETE_STORY = "DELETE_STORY";
const EDIT_STORY = "EDIT_STORY";
const EDIT_HISTORY = "EDIT_HISTORY";
const USER_VOTE = "USER_VOTE";
const FLIP_CARDS = "FLIP_CARDS";
const DELETE_VOTES = "DELETE_VOTES";
const END_GAME = "END_GAME";
const RESET_TIMER = "RESET_TIMER";
const WEBSOCKET_CONNECT = "WEBSOCKET_CONNECT";
const WEBSOCKET_OPEN = "WEBSOCKET_OPEN";
const WEBSOCKET_CLOSE = "WEBSOCKET_CLOSE";
const WEBSOCKET_MESSAGE = "WEBSOCKET_MESSAGE";
const WEBSOCKET_SEND = "WEBSOCKET_SEND";
const WEBSOCKET_DISCONNECT = "WEBSOCKET_DISCONNECT";
const WEBSOCKET_ERROR = "WEBSOCKET_ERROR";
export const ADD_TOAST = "ADD_TOAST";
export const REMOVE_TOAST = "REMOVE_TOAST";
export const LOGIN = "LOGIN";
export const LOGIN_SUCCES = "LOGIN_SUCCES";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export {
  CREATE_ROOM,
  JOIN_ROOM,
  REJOIN_ROOM,
  START_GAME,
  NEW_MEMBER,
  ADD_VOTE,
  ADD_STORY,
  DELETE_STORY,
  EDIT_STORY,
  EDIT_HISTORY,
  USER_VOTE,
  FLIP_CARDS,
  DELETE_VOTES,
  END_GAME,
  RESET_TIMER,
  WEBSOCKET_CONNECT,
  WEBSOCKET_OPEN,
  WEBSOCKET_CLOSE,
  WEBSOCKET_MESSAGE,
  WEBSOCKET_DISCONNECT,
  WEBSOCKET_SEND,
  WEBSOCKET_ERROR
};
