const CREATE_ROOM = "CREATE_ROOM";
const UPDATE_ROOM = "UPDATE_ROOM";
const NEW_MEMBER = "NEW_MEMBER";
const ADD_VOTE = "ADD_VOTE";
const RENAME_ROOM = "RENAME_ROOM";
const ADD_STORY = "ADD_STORY";
const START_STORY = "START_STORY";
const END_STORY = "END_STORY";
const DELETE_STORY = "DELETE_STORY";
const EDIT_STORY = "EDIT_STORY";
const EDIT_HISTORY = "EDIT_HISTORY";
const USER_VOTE = "USER_VOTE";
const FLIP_CARDS = "FLIP_CARDS";
const DELETE_VOTES = "DELETE_VOTES";
const END_GAME = "END_GAME";
const RESET_TIMER = "RESET_TIMER";
const WEBSOCKET_CONNECT = "WEBSOCKET_CONNECT";
const WEBSOCKET_OPEN = "WEBSOCKET_OPEN";
const WEBSOCKET_CLOSE = "WEBSOCKET_CLOSE";
const WEBSOCKET_MESSAGE = "WEBSOCKET_MESSAGE";
const WEBSOCKET_SEND = "WEBSOCKET_SEND";
const WEBSOCKET_DISCONNECT = "WEBSOCKET_DISCONNECT";
const WEBSOCKET_ERROR = "WEBSOCKET_ERROR";
const WEBSOCKET_RECONNECTED = "WEBSOCKET_RECONNECTED";
const WEBSOCKET_RECONNECTING = "WEBSOCKET_RECONNECTING";
export const ADD_TOAST = "ADD_TOAST";
export const REMOVE_TOAST = "REMOVE_TOAST";
export const LOGIN = "LOGIN";
export const LOGIN_SUCCES = "LOGIN_SUCCES";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const GAME_STARTING = "GAME_STARTING";
export const GAME_STARTED = "GAME_STARTED";
export const GAME_FAILURE = "GAME_FAILURE";
export const FLIP_STARTING = "FLIP_STARTING";
export const FLIP_SUCCESS = "FLIP_SUCCESS";
export const FLIP_FAILURE = "FLIP_FAILURE";
export const CLEAR_STARTING = "CLEAR_STARTING";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const CLEAR_FAILURE = "CLEAR_FAILURE";
export const END_STARTING = "END_STARTING";
export const END_SUCCESS = "END_SUCCESS";
export const END_FAILURE = "END_FAILURE";
export const RESET_STARTING = "RESET_STARTING";
export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_FAILURE = "RESET_FAILURE";
export const REMOVE_MEMBER = "REMOVE_MEMBER";

export {
  CREATE_ROOM,
  UPDATE_ROOM,
  NEW_MEMBER,
  ADD_VOTE,
  ADD_STORY,
  START_STORY,
  END_STORY,
  RENAME_ROOM,
  DELETE_STORY,
  EDIT_STORY,
  EDIT_HISTORY,
  USER_VOTE,
  FLIP_CARDS,
  DELETE_VOTES,
  END_GAME,
  RESET_TIMER,
  WEBSOCKET_CONNECT,
  WEBSOCKET_OPEN,
  WEBSOCKET_CLOSE,
  WEBSOCKET_MESSAGE,
  WEBSOCKET_DISCONNECT,
  WEBSOCKET_SEND,
  WEBSOCKET_ERROR,
  WEBSOCKET_RECONNECTED,
  WEBSOCKET_RECONNECTING
};
